[package]
name = "bbfs-api"
version = "0.1.0"
edition = "2021"

[target."cfg(unix)".dependencies]
nix.workspace = true

[target."cfg(windows)".dependencies]
winapi = { workspace = true, features = ["ntdef"] }
