[package]
name = "bbfs-dokan"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
bbfs-scrape.workspace = true
camino = "1.1.6"
dokan = "0.3.1"
widestring = "0.4.3"
winapi.workspace = true
