[package]
name = "lib-bb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
serde = { version = "1.0.186", features = ["derive"] }
serde_json = "1.0.105"
soup = "0.5.1"
