[package]
name = "bbfs-fuse"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
bbfs-api.workspace = true
dotenv = "0.15.0"
fuser = "0.13.0"
libc = "0.2.147"
nix = { workspace = true, features = ["user"] }
